package com.kodilla.clinic.backend.enums;

public enum Hour {
    EIGHT_AM, EIGHT_THIRTY_AM,
    NINE_AM, NINE_THIRTY_AM,
    TEN_AM, TEN_THIRTY_AM,
    ELEVEN_AM, ELEVEN_THIRTY_AM,
    TWELVE_PM, TWELVE_THIRTY_PM,
    ONE_PM, ONE_THIRTY_PM,
    TWO_PM, TWO_THIRTY_PM,
    THREE_PM, THREE_THIRTY_PM,
    FOUR_PM, FOUR_THIRTY_PM,
    FIVE_PM, FIVE_THIRTY_PM,
    SIX_PM, SIX_THIRTY_PM,
    SEVEN_PM, SEVEN_THIRTY_PM
}
