package com.kodilla.clinic.backend.enums;

public enum Specialization {
    DERMATOLOGY, VENEREOLOGY, INTERNAL_DISEASES, CARDIOLOGY, CARDIOSURGERY, PAEDIATRICS, LARYNGOLOGY, OPHTHALMOLOGY,
    NEUROLOGY, PSYCHIATRY, PSYCHOLOGY, CHILD_PSYCHIATRY
}
