package com.kodilla.clinic.backend.enums;

public enum SymptomName {
    ABDOMINAL_PAIN, ANXIETY, BACK_PAIN, CHEST_PAIN, COUGH, DIZZINESS, FEVER, HEADACHE, MENSTRUATION_DISORDER,
    NERVOUSNESS, PARALYSIS, SLEEPLESSNESS, SWEATING, TIREDNESS, TREMOR_AT_REST, UNCONSCIOUSNESS_SHORT, VOMITING_BLOOD,
    WEAKNESS, WEIGHT_GAIN
}